config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  root to: 'books#index'

  post 'books/add_to_cart/:id', to: 'books#add_to_cart', as: 'add_to_cart'
  delete 'books/remove_from_cart/:id', to: 'books#remove_from_cart', as: 'remove_from_cart' 
  post 'books/checkout_cart', to: 'books#checkout_cart', as: 'checkout_cart'

  resources :books do 
    resources :reviews
  end
  
end

app/models/album.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :price, presence: true 

  before_save(:titleize_book)

  private
    def titleize_book
      self.title = self.title.titleize
    end
end

app/models/application_record.rb
class ApplicationRecord < ActionController::API
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user 

  validates :title, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :price, presence: true 
  validates :user_id, presence: true

  before_save(:titleize_book)

  def self.books_by_user(user) 
    where(:user_id => user)
  end

  def self.books_not_by_user(user)
    where(:user_id != user)
  end

  private
    def titleize_book
      self.title = self.title.titleize
    end
    
end

app/models/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :content_body, presence: true, length: { within: 10..50 }
  validates :rating, presence: true, numericality: { integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  respond_to :html, :json
  include Response
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :intialize_session
  before_action :increment_visit_count
  before_action :load_cart
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    if current_user
      @books_by_user = Book.books_by_user(current_user.id)
      @book = Book.all
      render :index
    else 
      @book = Book.all
    end
  end

  def new 
    @book = Book.new
    render :sell
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Product successfully added!"
      redirect_to books_path
    else
      render :sell, status: :unprocessable_entity
    end

  end

  def show
    @book = Book.find(params[:id])
    user = User.find(@book.user_id)
    @user_email = user.email
    render :show
  end

  def update
    @book = Book.find(params[:id])
    if @book.update!(book_params)
      render status: 200, json: {
        message: "This book has been updated successfully."
      }
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book has been deleted."
    redirect_to root_path
  end

  def add_to_cart 
    id = params[:id].to_i 
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to root_path
  end 

  def remove_from_cart 
    id = params[:id].to_i 
    session[:cart].delete(id)
    redirect_to root_path
  end

  def total_cart(arr) 
    processing_array = []
    for i in arr
        while arr.length > 0  
          processing_array.push(i) 
          arr.pop(i)
        end
    end
    return processing_array.sum * 1.0875
  end

  def checkout_cart 

    for i in session[:cart] 
      book = Book.find(i) 
      total_array = []
      total_array.push(book.price) 
      buying_user_id = current_user.id  
      buying_user = User.find(buying_user_id) 

      if buying_user.wallet_balance < total_cart(total_array)  
        session[:cart].clear
        flash[:notice] = "You have insufficient funds to make this purchase." 
      else
        while session[:cart].length > 0
          book_user_id = book.user_id 
          selling_user = User.find(book_user_id)

          deducted_new_balance = buying_user.wallet_balance -= book.price 
          credited_new_balance = selling_user.wallet_balance +=  book.price 

          buying_user.update({:wallet_balance => deducted_new_balance})
          selling_user.update({:wallet_balance => credited_new_balance})
          
          book.update({:sold => true})  
          book.update({:user_id => buying_user.id})
          session[:cart].pop(i)
          end
      end
      redirect_to root_path
    end

  end


  
  private

  def intialize_session 
    session[:visit_count] ||= 0 
    session[:cart] ||= []
  end

  def load_cart
    @cart = Book.find(session[:cart])
  end

  def increment_visit_count 
    session[:visit_count] += 1 
    @visit_count = session[:visit_count] 
  end

  def book_params
    params.require(:book).permit(:title, :author, :genre, :price, :user_id)
  end

  def json_response(object, status = 401)
    render json: object, status: status
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]
  before_action :only => [:edit, :show] do
    render :error unless current_user && current_user.admin 
  end

  def new
    @book = Book.find(params[:book_id])
    @review = @book.reviews.new
    render 'books/show'
  end

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.new(review_params)
    @review.user_id = current_user.id  
    if @review.save
      redirect_to product_path(@book)
    end
    render 'books/show'
  end

  def edit
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
    render 'books/show'
  end

  def show
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:id])
    render 'books/show'
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to books_path(@review.book)
    else
      @review = Book.find(params[:album_id])
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review has been deleted."
    redirect_to books_path(@review.book)
  end

  private
  def review_params
    params.require(:review).permit(:content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/complete_order_page.erb
<% if current_user %> 

  <h1> Thanks for shopping at BookBay,<% current_user.email %>  

  <h3> Your order summary <h3> 

  <ul>
    <% @cart.each do |book| %>
      <li><%= book.title %> / $<%= number_with_precision book.price, precision: 2 %></li>
    <% end %>
  </ul>

   <% total_price = []%>
              <%@cart.each do |book| %>
                <% total_price.push(book.price)%>
   <% end %>
  <p>Subtotal: $<%= number_with_precision (total_price).sum, precision: 2%><p>
  <p>-----------</p>
  <p>+ CA Sales Tax: $<%= number_with_precision (total_price).sum * 1.0875 - (total_price).sum, precision: 2%><p>
  <p>-----------</p>
  <p>Final Total: $<%= number_with_precision (total_price).sum * 1.0875, precision: 2%><p>

  <p>$<%= number_with_precision (total_price).sum * 1.0875, precision: 2%> was charged to your account.</p>

<% else %> 
  <p>How did you get here? You did not buy anything yet!</p>
<% end %>

app/views/books/index.html.erb
<section class = "section">
  <% if current_user%>
    <div class = "box">
      <h2 class = "title is-2"> Your Cart </h2>
        <% if @cart.empty? %> <p> You cart is empty!</p><% else %> <div class="box">
          <ul><% @cart.each do |book| %> <li><%= book.title %> / $<%= number_with_precision book.price, precision: 2 %> <p><%= button_to  '- remove from cart', remove_from_cart_path(book), method: :delete%> </p>
            </li><% end %> </ul>
        </div>
        <% total_price = []%><%@cart.each do |book| %><% total_price.push(book.price)%><% end %> 
        <div class = "box">
          <p>Subtotal: $<%= number_with_precision (total_price).sum, precision: 2%>
          <p>+ CA Sales Tax: $<%= number_with_precision (total_price).sum * 1.0875 - (total_price).sum, precision: 2%>
          <p>Final Total: $<%= number_with_precision (total_price).sum * 1.0875, precision: 2%>
          <p><%= button_to  'checkout', checkout_cart_path, method: :post%> </p>
        </div>
      <p><% end %>   
    </div>
    <div class = "columns is-mobile">
      <div class = "column">
        <div class = "box">
          <h2 class = "title is-2">Your Books</h2>
          <% if @books_by_user.any? %>
            <ul>
              <% @books_by_user.each do |book| %>
                <li><%= link_to book.title, book_path(book) %></li>
              <% end %>
            </ul>
          <%end%>
        </div>
      </div>
      <div class = "column">
        <div class = "box">
            <h2 class = "title is-2">Books</h2>
            <% if @book.any? %>
                <% @book.each do |book|%>
                  <% if book.user_id != current_user.id%>
                    <li><%= link_to book.title, book_path(book) %></li>
                  <% end %>
                <% end %>
            <% else %>
              <p>There are no books yet.</p>
            <% end %>
          </div>
      </div>
    </div>
        <div class = "column">
        </div>
      </div>
      </div>
      <% else %>
        <div class = "box">
          <h2 class = "title is-2">Books</h2>
          <% @book.each do|book|%>
            <li><%= link_to book.title, book_path(book) %></li> 
        <% end %>
        </div>
  <%end%>
</section>

app/views/books/sell.html.erb
<h1>List a new book to sell</h1>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit  %>
<% end %>

<% if @book.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  
<% end %>

app/views/books/show.html.erb
<h1>Book: <%= @book.title %></h1>
<h3>Author: <%= @book.author %></h3>
<h3>Genre: <%= @book.genre %></h3>
<h3>Price: $<%= number_with_precision @book.price, precision: 2 %></h3>
<% if current_user %>

  <% if @user_email == current_user.email %>
    <p>Listed: You </p>
  <% else %>
    <p>Listed: <%= @user_email %></p>
  <% end %>

  <% if @cart.include?(@book)%>
    <p>Book is in your cart.</p>
    <p><%= button_to  'remove from cart', remove_from_cart_path(@book), method: :delete%></p>
  <% elsif @book.sold == true &&  @user_email != current_user.email %>
    <p><%= button_to  'add to cart', add_to_cart_path(@book.id), method: :post%></p>
  <% elsif @user_email == current_user.email %>
      <%= button_to "Remove this listing", 
                book_path(@book),
                method: :delete %> 
  <% else %>
    <p><%= button_to  'add to cart', add_to_cart_path(@book.id), method: :post%></p>
  <% end %>
  
  <% if @book.reviews.any? %>
     <% @book.reviews.each do |review| %>
      <ul>
        <li>
         <%= review.user_id %>
        |
        Review: <%= review.content_body%>
        | 
        Rating: <%= review.rating %> 
        </li>
      </ul>
    <% end %>
  <% else %>
    <p>There are no reviews listed for this product.</p>
  <% end %>
  

<% else %>
  <p>Sign in to leave a review or add this item to your cart.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookbay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1"><%# <%= csrf_meta_tags %><%= csp_meta_tag %><%= stylesheet_link_tag "application", "data-turbo-track": "reload" %><%= javascript_importmap_tags %>
  </head>
  <body>
    <section class="hero is-primary">
      <div class="hero-body">
        <div class="columns">
          <div class="column is-half">
            <h1 class="title is-1">BookBay</h1>
          </div>
            <% if current_user %> 
            <div class = "column">
              <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                  <li><p>Welcome, <%= current_user.email %> !</p></li>
                  <li><p>Wallet Balance: $<%= number_with_precision current_user.wallet_balance, precision: 2  %></p></li>
                  <li><%= link_to "Sell",new_book_path, method: :get %> 
                  </li>
                  <li><%= button_to "Log out",destroy_user_session_path(@user),method: :delete %></li>
                </ul>
              </nav>
            </div>
            <% else %>
                <nav class="breadcrumb" aria-label="breadcrumbs">
                  <li><p>Sign in/Sign up to add items to your cart or leave reviews!</p></li>
                  <li><%= link_to "Sign in",new_user_session_path, method: :get  %></li>
                  <%= link_to "Sign up", new_user_registration_path, method: :get  %></li>
                </nav>
            <% end %>
            </div>
          </div>
        </div>
      </div>
      </div>
    </section><%= flash[:alert] %><%= flash[:notice] %><%= yield %> <p> You have visited this site <%= pluralize @visit_count, 'time'%> </p>
  </body>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Bulma</strong> by <a href="https://jgthms.com">Paul Srisawat</a>. The source code is licensed <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </footer>
</html>